export const enum FetchTags {
  CategoriesList = 'CATEGORIES_LIST',
  UnitsList = 'UNITS_LIST',
  ProductsList = 'PRODUCTS_LIST',
  OrderList = 'ORDER_LIST',
  PaymentMethod = 'PAYMENT_METHOD',
  BannersList = 'BANNERS_LIST',
  BarcodeDiscount = 'DISCOUNT_LIST',
  OffersList = 'OFFERS_LIST',
  NotificationList='Notification_List',
  WorkArea = 'WORK_AREA',
  DriversList = 'DRIVERS_LIST',
  ClientsList = 'CLIENTS_LIST',
  EmployeesList = 'EMPLOYEES_LIST',
  ReportsOrdrersList = 'REPORTS_ORDERS_LIST',
  StaticPages = 'STATIC_PAGES',
  PrivacyPolicy = 'PRIVACY_POLICY',
  ContactUs = 'CONTACT_US',
  DriverOrder = 'DRIVER_ORDER',
  MostPurchased = 'MOST_PURCHASED',
  SalesRenveu = 'SALES_RENVEU',
  HomeSettings = 'HOME_SETTINGS',
  UpdateProfile='UPDATE_PROFILE',
  viewProfile='VIEW_PROFILE',
  DeliveryFees='DELIVERY_FEES',
}
